version: '3'

services:
  node:
    image: 'express_image'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_container
    volumes:
      - ./:/projects/enrollment-application
      - /projects/enrollment-application/node_modules
    ports:
      - 3000:3000
    networks:
      - enrollment-application

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - 27017:27017
    volumes:
      - mongo_data_container:/data/db
    networks:
      - enrollment-application

networks:
  enrollment-application:
    driver: bridge

volumes:
  mongo_data_container: